### ISSUE TITLE
Error with minetest 0.4.17.1

### ISSUE THREAD

**Issue by R-0ne** [poikilos/slimenodes#1]
hello, there is an error at launch with version 0.4.17.1 of minetest

```
WARNING[Main]: Undeclared global variable "bucket" accessed at ...netest-0.4.17.1-win64\bin\..\mods\slimenodes/buckets.lua:21
 ERROR[Main]: ModError: Failed to load and run script from C:\Users\r-one\Desktop\minetest-0.4.17.1-win64\bin\..\mods\slimenodes\init.lua:
ERROR[Main]: ...netest-0.4.17.1-win64\bin\..\mods\slimenodes/buckets.lua:21: attempt to index global 'bucket' (a nil value)
 ERROR[Main]: stack traceback:
ERROR[Main]: 	...netest-0.4.17.1-win64\bin\..\mods\slimenodes/buckets.lua:21: in main chunk
ERROR[Main]: 	[C]: in function 'dofile'
 ERROR[Main]: 	...\minetest-0.4.17.1-win64\bin\..\mods\slimenodes\init.lua:231: in main chunk
ERROR[Main]: Voir debug.txt pour plus d'informations.

```

**Comment by Poikilos** [comment]
I hear minetest.net's 0.4.17 has some breaking changes that must have been backported from 5.0.0, and even though this worked with 5.0.0-dev from March or so, there must be something I don't know. I also hear that minetest.org will [start making releases](https://minetest.org/features.html) that retain backward compatibility. I plan to eventually have compatibility with both.

**Comment by Poikilos** [comment]
It was a dependency issue (intermittent, depending on whether the "bucket" mod was loaded yet). Now that I've added "bucket" to depends.txt, the issue is resolved as per my testing. Sorry it took so long to fix.

**Comment by Poikilos** [comment]
@R-0ne Oh are you red-001? You didnt have many repos on here which was a surprise since your name sounds like red-001, one of the top Minetest devs.

**Comment by poikilos** [comment]
Sorry it took so long to fix.
